### PR TITLE
[DRAFT]: TestMR, Updating setting to what is needed for local runs. Just for t…

### PR DESCRIPTION
**Pull request by prichard77**
…testing the pr_check for ingress
I am debugging an issue with a new test and needed to create an MR. 
TEST ONLY. Do not Merge.

## What?
Explain what the change is linking any relevant JIRAs or Issues.

## Why?
Consider what business or engineering goal does this PR achieves.

## How?
Describe how the change is implemented. Any noteable new libaries, APIs, or features.

## Testing
Did you add any tests for the change?

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3f36a532-4d69-4b01-bca0-09b3d879352a
5e34d72c-8186-4895-8828-9ec87051813f

**Comment by prichard77** [comment]
Looks like this will not be the solution we want to use to fix the issue. I was trying to be proactive. I am closing this MR.

**Comment by prichard77** [comment]
Testing again.

**Comment by prichard77** [comment]
This was a test PR

**Pull request closed without merging**
