### PR TITLE
[deps] update to middlewares v0.16.1

### PR DESCRIPTION
**Pull request by SteveHNH**
Signed-off-by: Stephen Adams <stephen.adams@redhat.com>

## What?
Fix a bug in platform-go-middlewares

## Why?
This will eliminate the 400 error issues we've been seeing since yesterday

## How?
The middlewares package was updated to properly type the AuthTime value into a float

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
6e82f6c6-62cb-4abe-9034-de5f62478824
f52777d2-6b3e-4306-9f94-717162beb6b2

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
03120e9a-fade-4d8d-9972-80b693b770d5
05e90773-320d-44b7-bb79-074fe8093aa0

**Review by aleccohan — APPROVED** [review]
LGTM

**Pull request merged**
