### PR TITLE
Log metadata field

### PR DESCRIPTION
**Pull request by tremes**
## What?
This is adding `metadata` field to the log output

## Why?
I don't have a strong opinion here but I think it can be useful

## How?
Describe how the change is implemented. Any noteable new libaries, APIs, or features.

## Testing
Just test locally

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by SteveHNH** [comment]
OH man, I hate it's taken so long for me to swing around to this. We've been trying to keep the logging lower since we have to pay for the amazon logging service. This would log the metadata for every incoming message which could be a lot. Logging it in the event of an error sounds like something that would give us a more reasonable amount of logging.

**Comment by tremes** [comment]
I completely forgot about this PR. I am just reading the comment from Stephen and the suggestion is to move it to log only in case of error right? I think I am also fine with closing this PR.... :) You tell me guys. Thanks

**Comment by SteveHNH** [comment]
@tremes Thanks for the PR! I'm going to go ahead and close it.

**Pull request closed without merging**
