### PR TITLE
Add aap-eda mime type for uploads

### PR DESCRIPTION
**Pull request by hsong-rh**
## What?
Add aap-eda to the upload mime types

https://issues.redhat.com/browse/AAP-30055

### CODE REVIEW

**Comment by dehort** [comment]
@hsong-rh This change looks fine.  Do you know how big the uploads will be?  How frequently will the uploads be sent?  How many hosts will be sending the uploads and over what time period?

**Comment by hsong-rh** [comment]
> @hsong-rh This change looks fine. Do you know how big the uploads will be? How frequently will the uploads be sent? How many hosts will be sending the uploads and over what time period?

@dehort We will use the [insights-analytics-collector](https://github.com/RedHatInsights/insights-analytics-collector) repo to collect and upload data. The maximum file size is 100MB. For a big table, it may be split into multiple files. The collection will be scheduled every 4 hours. So far we only have one scheduler host.

**Comment by hsong-rh** [comment]
@dehort Any suggestions for this PR to be merged?

**Comment by dehort** [comment]
@hsong-rh right now you only have upload coming from one host.  Is that right?  How many hosts do you expect to be uploading these files in the future?

**Comment by hsong-rh** [comment]
> @hsong-rh right now you only have upload coming from one host. Is that right? How many hosts do you expect to be uploading these files in the future?

Yes, there is only one host now. For the future, I am not sure, @Ladas may have answers.

**Comment by Ladas** [comment]
@dehort the estimate is that max few hundreds of hosts would be sending data. (up to ±1500 longer term)

By default they will send data every 4h. The payload size per host is yet to be determined. (shouldn't be large from start)

**Comment by Ladas** [comment]
@dehort quick question, should this be autoreleased on Stage already? (and we need manual prod deploy scheduled?)

**Comment by dehort** [comment]
@Ladas It should have been autoreleased to Stage, but it looks like it didn't.  I'll look into getting this pushed out to stage tomorrow.

**Comment by hsong-rh** [comment]
@dehort thank you, please let us know when it's pushed

**Comment by dehort** [comment]
@Ladas @hsong-rh this change has been deployed to stage.  I am not sure why it didn't work previously.  :shrug:

**Comment by hsong-rh** [comment]
> @Ladas @hsong-rh this change has been deployed to stage. I am not sure why it didn't work previously. 🤷

@dehort It worked now, I saw the log record in the Kibana board. thank you!

**Pull request merged**
