### PR TITLE
RHCLOUD-18521: Update announce topic to accept anemic tenants

### PR DESCRIPTION
**Pull request by aleccohan**
## What?
Allow the announce topic to accept anemic tenants.

## Why?
With all dependencies now at level 2 support for EBS account --> org_id migration, all that was left was to allow the announce (single topic) to accept anemic tenants so that all dependencies can swap over to it whenever they are ready for the level 3 migration.

## How?
Added a check when the channels are being updated to allow anemic tenants to be accepted by the announce topic and all other requests (Account number + org_id) to go to both the announce topic and the single service topics.

## Testing
Added Unit Testing for successful request with an anemic-tennant.

## Anything Else?
JIRA:  https://issues.redhat.com/browse/RHCLOUD-18521

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
caa2155f-2d86-4f43-8688-7b0acabda212
febf03f5-0de8-4967-962a-20f5997680d9

**Review by SteveHNH — APPROVED** [review]
looks good to me!

**Comment by SteveHNH** [comment]
approved!

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
b32b17c5-05c5-4941-b9ac-9d300db8b338
c5db93d4-1286-4fc6-87fd-1952deed9e98

**Pull request merged**
